### ISSUE TITLE
Install nimble

### ISSUE THREAD

**Issue by andreaferretti** [ekarlso/nim-vm#12]
It would be nice to be able to install [nimble](https://github.com/nim-lang/nimble) with `nim-vm` as well.

Once nimble is installed, everything else can be installed through nimble, including nimble itself (`nimble install nimble@#head`).

But installing nimble while using nim-vm is a little inconvenient. First, not every version pair is compatible - in particular nimble 0.7 requires nim 0.13 at least, so it will fail when switching to older nim versions.

More important, even if one uses nim-vm to update devel, and occasionally check if something works with the latest stable (which is my use case), [installing nimble](https://github.com/nim-lang/nimble#unix) is still a little manual work. It would be nice to be able to tell people to install nim-vm and be ready to use the whole ecosystem.

**Comment by oderwat** [comment]
True. I may add that as a features to nim-vm soon. I guess we need to add some kind of compatibility list such that nim-vm knows what nimble version should get installed. Have to investigate!

**Comment by andreaferretti** [comment]
I was starting to collect some compatibility list, but the fact is that nimble install itself, so once one upgrades nimble via nimble, it is outside of control of nim-vm.

I think the simplest thing would be to add a task like `nim-vm nimble` that just installs latest nimble (maybe checking that the nim in use has version at least 0.13), and after that users can install older versions of nimble using nimble if needed.

Actually, it may be that latest nimble requires recent versions of nim to build, but then the binary works with older versions, so older nimbles are not needed anyway

**Comment by andreaferretti** [comment]
Any update on this? I would do it myself, but I am not an expert in shell scripting, especially cross-platform.

What do you think of the proposal of just adding the functionality to install nimble, without tying the nimble version to the nim version?

Nimble will manage itself after the install anyway, so it would be difficult to change Nimble version when changing Nim version. But having a quick, simple way to install Nim and Nimble would go a long way towards helping newcomers getting started

**Comment by oderwat** [comment]
Well... I gave it a try. See PR #14 .. But I did not test this on other than my system. It just installs Nimble really "dumb" and adds the path (which is the harder part)

**Comment by andreaferretti** [comment]
I tried it on my Ubuntu and it works fine

**Comment by andreaferretti** [comment]
As this tool is now superseded by choosenim, I am closing the issue
